# Rebuild indexes from the existing internal tables, or from the tables just
# generated by internal_data.R. No source downloads are needed.
devtools::load_all()
source("data-raw/index-helpers.R")
indexes <- build_glydb_indexes()
concrete_composition_index <- indexes$composition$concrete
generic_composition_index <- indexes$composition$generic
intact_concrete_structure_index <- indexes$structure$intact$concrete
intact_generic_structure_index <- indexes$structure$intact$generic
topological_concrete_structure_index <- indexes$structure$topological$concrete
topological_generic_structure_index <- indexes$structure$topological$generic

usethis::use_data(
  concrete_composition_index,
  generic_composition_index,
  intact_concrete_structure_index,
  intact_generic_structure_index,
  topological_concrete_structure_index,
  topological_generic_structure_index,
  concrete_comps,
  generic_comps,
  intact_concrete_strucs,
  topological_concrete_strucs,
  intact_generic_strucs,
  topological_generic_strucs,
  struc_glytoucan_lookup,
  internal = TRUE,
  overwrite = TRUE
)
